using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace AMMS.Application.Helpers
{
    public static class LibreOfficePdfConverter
    {
        public static async Task<byte[]> ConvertDocxBytesToPdfAsync(
            byte[] docxBytes,
            ILogger logger,
            CancellationToken ct = default)
        {
            if (docxBytes == null || docxBytes.Length == 0)
                throw new ArgumentException("DOCX bytes is empty");

            var workDir = Path.Combine(Path.GetTempPath(), "amms-receipt-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(workDir);

            try
            {
                var inputDocx = Path.Combine(workDir, "input.docx");
                var outputPdf = Path.Combine(workDir, "input.pdf");

                await File.WriteAllBytesAsync(inputDocx, docxBytes, ct);

                var userProfileDir = Path.Combine(workDir, "lo-profile");
                Directory.CreateDirectory(userProfileDir);

                var psi = new ProcessStartInfo
                {
                    FileName = "soffice",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                psi.ArgumentList.Add("--headless");
                psi.ArgumentList.Add($"-env:UserInstallation=file://{userProfileDir.Replace("\\", "/")}");
                psi.ArgumentList.Add("--convert-to");
                psi.ArgumentList.Add("pdf:writer_pdf_Export");
                psi.ArgumentList.Add("--outdir");
                psi.ArgumentList.Add(workDir);
                psi.ArgumentList.Add(inputDocx);

                using var process = new Process { StartInfo = psi };

                process.Start();

                var stdOutTask = process.StandardOutput.ReadToEndAsync(ct);
                var stdErrTask = process.StandardError.ReadToEndAsync(ct);

                await process.WaitForExitAsync(ct);

                var stdOut = await stdOutTask;
                var stdErr = await stdErrTask;

                if (process.ExitCode != 0)
                {
                    logger.LogError(
                        "LibreOffice convert failed. ExitCode={ExitCode}, StdOut={StdOut}, StdErr={StdErr}",
                        process.ExitCode, stdOut, stdErr);

                    throw new InvalidOperationException(
                        $"LibreOffice convert failed. ExitCode={process.ExitCode}. StdErr={stdErr}");
                }

                if (!File.Exists(outputPdf))
                {
                    logger.LogError(
                        "LibreOffice convert did not produce PDF. StdOut={StdOut}, StdErr={StdErr}",
                        stdOut, stdErr);

                    throw new FileNotFoundException("PDF file was not generated by LibreOffice.");
                }

                return await File.ReadAllBytesAsync(outputPdf, ct);
            }
            finally
            {
                try
                {
                    if (Directory.Exists(workDir))
                        Directory.Delete(workDir, recursive: true);
                }
                catch
                {
                    // bỏ qua lỗi cleanup
                }
            }
        }
    }
}
